name: ccmi-cdt.io
remote_theme: pages-themes/cayman@v0.2.0
description: EPSRC Centre for Doctoral Training in Collaborative Computational Modelling at the Interface
background-image: https://liveuclac-my.sharepoint.com/:i:/r/personal/ccaejja_ucl_ac_uk/Documents/Desktop/logo%20test.png?csf=1&web=1&e=DYPOdK
