---
title: "Application Procedure"
---

The application procedure consists of the following four steps.

1.) **The online application.** We ask you to submit an application to our online submission system. Based on your application we will make a first sift of the candidates and invite shortlisted candidates for interview.

2.) **The Interview.** For the interview we will ask you to prepare a short presentation and answer a mixture of questions covering technical background and your motivation to join the CDT. The interview questions will be communicated to applicants beforehand so that they have sufficient time to prepare for the technical and non-technical part.

3.) **The project matching**. Once you pass the interview we aim to match you with a supervisor. We will prepare an online info session about the different research areas of the CDT and you have opportunities to ask questions and discuss project choices. Your project will decide wether you will be enrolled at UCL or Imperial College. Every student can submit three preferred project choices. We will circulate your information after the interview stage with the corresponding supervisors and you can also discuss the projects directly with them. If both, you and the supervisor come together for one of your preferred projects you are matched and you proceed to the offer stage. If none of your three preferred projects leads to a match we will suggest another project for you based on your background. Should you accept you will proceed to the offer stage. If no match with a project/supervisor is possible you will not receive an offer.

4.) **The offer stage**. You will be asked to submit a pro-forma application to either UCL or Imperial depending on your project match. This is only to make a formal document check about information you have submitted beforehand and to receive a formal offer from your chosen university on successful document check. The offer may be conditional on language test and the outcome of your current degree if you haven't finished your previous studies at the time of application to the CDT.

