---
title: "Interview preparation"
---

This page collects some information for applicants who have been shortlisted to the interview stage. 


### Time and Location

The next round of interviews takes place 12/13 February. Applicants will be sent an online invite for a Zoom interview
with a timeslot in those two days. All interviews are online.

### Interview panel

The panel for each interview will consist of two to three academic members of staff across UCL and Imperial.

### The setup of the interview

The interview will be roughly 30-35 minutes in length and consist of three parts.

- A technical part to assess the technical knowledge of applicants. Below we have a list of publications. We ask you to
select **one** of these publications and give a 5 minutes presentation about the key results of the publication. We will then
spend 10 minutes to ask you more topical questions about the area of the publication. So that you can prepare we have collected
relevant topic areas for each publication below. Please note that we will be probing your knowledge. But we do not expect that you can give in-depth answers to everything.
- A discussion on your fit to the CDT (around 7 minutes). We will ask you about your motivation to join the CDT, how you would
contribute to the software journey, and how your previous experience helps you with the software journey. Detailed info about
the software journey programme of the CDT is given below.
- Finally, we discuss relevant research areas for you (around 8 minutes). This is to get an indication about the kind of PhD projects
that would be most suitable for you. We want to know what areas you are most interested in and why. We will ask you how a PhD helps
your desired career path, and how your previous education has prepared you to do research on a PhD level in your desired research area.

### What to expect after the interview?

We are aiming to make decisions within a few days after your interview. If after the interview you are shortlisted for project selection there will be a two weeks getting to know phase, in which you can talk to supervisors, discuss projects in detail with us, and can get
to know potential supervisors at open events. By the end of this phase we will ask you to submit your preferred PhD topics. We will aim
to accommodate those and guide you to a PhD project that is most suitable for you. Once you and a supervisor are matched for a PhD project you will need to submit a pro-forma application to either UCL or Imperial so that the universities can do a proper document check, confirm
your fee status and create an offer for a place in the CDT. Note that a place in the CDT is guaranteed only once the offer is sent out.

If you have not been shortlisted after interview you may be put on a reserve list. We will let those on the reserve list also quickly now and keep regular updates about their status. Not all formal offers for a PhD will be taken up by students. So there is a good chance on the reserve list to be offered a place a little bit later.

If you are neither shortlisted nor on the reserve list we are unfortunately not able to offer you a place in the CDT for this year. But you are very welcome to apply for future entry. If requested we will be very happy to try and provide feedback for your interview so that you have advise for other PhD interviews in the future.

### Preparation Material for the Interview

We will ask you to give a 5 minutes presentation about one of the following papers. We have added some topical markers about what you may want to focus on.

- [Liberty et. al. *Randomized Algorithms for the low-rank approximation of matrices*](https://doi.org/10.1073/pnas.0709640104). This paper suggests two randomized algorithms to compute the Interpolative Decomposition of matrices. Questions to consider include: What is the Singular Value Decomposition and what is the Interpolative Decomposition (ID). Why is the ID useful? How is the ID computed by the two algorithms? How can we compute an SVD from this?
- [Turner, *An introduction to Transformers*](https://arxiv.org/pdf/2304.10557). This very recent paper describes the mathematical ideas of transformer neural networks. You are asked to describe the basic ideas behind transformers, their precise definition and how they are used in neural networks.
- [E, *A Proposal on Machine Learning via Dynamical
Systems*](https://link.springer.com/article/10.1007/s40304-017-0103-z). This paper discusses connections of dynamical systmems and deep learning. You should know how a dynamical system can be used to define a learning model, and be able to describe the optimal control in this context. You should also have a good intuition on how this connects to deep neural networks.

For your 5 minutes presentation please make sure that:

- You stay exactly within your 5 minutes. Practice your talk beforehand and time it. The best is to have a timer visible on your mobile phone or otherwise nearby.
- The presentation setup works, i.e. you can share your screen (especially on Mac make sure that under the Privacy Settings for Mac OS screen sharing is eanbled for Zoom.) Test your setup beforehand.
- You do not have too many slides. A typical beginner mistake is to have too many slides. You want to present the key ideas on a few slides. 5 minutes is not enough for a deep dive but gives you enough time to explain the main ideas.

For your interview you will also be asked how to contribute to the **Software Journey** in the CDT. The software journey has the following two key components.

- *A software bazaar* in which students, academics, and external partners can offer software projects, ranging from small extensions of existing software to larger open-source projects. Anything is possible. The conditions are that it is useful for a larger community and that it is defined with realistic goals for a small team (typically two to three) to work on.
- *A termly software week*. Once a term we have a software week in which members of the CDT present project pitches, their peers review proposals for MVPs (minimum viable products) and discuss the corresponding timelines. There will be joint sprint sessions to push projects forward, technical discussions and presentations to and talks from external partners.

Students will be mentored by professional research software engineers from UCL's Advanced Research Computing Centre for their own software journey. The expectation is that all students actively engage in projects and produce software not only as part of their PhD thesis but also contribute to other projects they are interested in.

Software projects will be actively advertised on the CDT homepage, at relevant conferences and showcased once a year at a CDT event for the broader community.

### Extenuating circumstances

If you have extenuating circumstances that require reasonable adjustments for the interview please let us know as soon as possible so that we can plan accordingly. If you are feeling ill on the day of the interview please also let us know straight away so we can work out alternative arrangements with you.

### A word of encouragement

All of us have gone through important interviews and all of us have been nervous and we are still getting nervous ourselves when interviewed for e.g. important grant applications or promotions. All of this is normal and does not work against you. So if you feel overwhelmed in the interview just stop for a moment and take a breezer. We all understand this and it is perfectly fine.
Should you feel too nervous in the interview we will try to give you break and continue later in the day if possible.
Create an environment that helps you relax and always remember, the interview is there to get to know you. You have already managed the hurdle of shortlisting. You have a lot to offer and you can be proud of it.