---
title: "Seminar on high order PDE solvers"
author: "Timo Betcke"
event_date: "05/12/2026"
date: "05/06/2026"
summary: "Prof Adrianna Gillman discusses fast and accurate high-order solvers for oscillatory PDEs."
categories: [News]
---

**LOCATION:** Function space, UCL AI Centre, 90 High Holborn, London WC1V 6BH

**TIME:** 14:00-15:00, 12/05/2026

**SPEAKER:** Adrianna Gillman (Inria)

**TITLE:** Modeling and simulation of cardiac hemodynamics  

**ABSTRACT:** 
For many applications in science and engineering, the ability to efficiently and accurately approximate solutions to elliptic PDEs dictates
what physical phenomena can be simulated numerically.  In this talk, we present a high-order accurate discretization technique
for variable coefficient PDEs with smooth coefficients. For two-dimensional problems, a direct solver that is inspired by the 
multifrontal method is scales linearly or nearly linear with respect to the number of unknowns. Unlike the application of multifrontal methods to classic discretization techniques, the constant prefactors do not grow with the order of the discretization. The discretization is robust even for problems with highly oscillatory 
solutions.  For example, a problem 100 wavelengths in size can be solved to 9 digits of accuracy with 3.7 million unknowns on a desktop
computer.  The precomputation of the direct solver takes 6 minutes on a desktop computer.  Then applying the computed solver takes 3 seconds.  A parallel implementation of the solution technique reduces the precomputation time to roughly 30 seconds and halves 
the time it takes to apply the solver.  Recent work making the solution technique viable for three-dimensional problems and some applications will be presented.   