---
title: "A Unified Solver for Optimal Transport, Schroedinger Bridges, and Variational Mean Field Games"

department: "Mathematics"

date: "10/02/2024"
author: 
    name: "Prof Colin Cotter and Dr. Dante Kalise"
    affiliation: "Imperial"
---
## Project Description

### Existing background work

Colin Cotter is Professor of Computational Mathematics at Imperial College. He has relevant interests in optimal transport applied to the semigeostrophic equations and to weather forecast verification, and in design, analysis and implementation of finite element methods.

Dante Kalise is Reader in Optimisation and Control at the Department of Mathematics at Imperial College. His main research interests involve scientific computation and machine learning, optimal control, high-dimensional approximation and agent-based models across scales. He has developed variational methods for mean field games and control which constitute the basis of this project, and developed applications in swarm robotics, pedestrian motion, and global optimization.

### Main objectives of the project

Starting from the fluid dynamics formulation of the Monge-Kantorovich mass transfer problem proposed by Benamou and Brenier, it is now well-understood that a wide class of problems including Optimal Transport (OT), Schroedinger Bridges (SB), Mean Field Control (MFC), and Variational Mean Field Games (MFG), can be seen as the solution of a PDE-constrained optimization problem where a convex cost if constrained to a continuity equation.  While the numerical approximation of these problems has been extensively studied over the last decade due to their importance in statistical machine learning, computational methods are often developed for a particular problem of interest and fail to identified the underlying unifying structure. 

In this project we will develop a unified solver for OT, SB, MFC and MFG, so that each instance arises after a suitable assignment of costs and constraints. The solver will be based on convex optimization methods (primal-dual algorithms), preconditioning, and structure-preserving discretizations of the continuity equation. 

### Details of Software/Data Deliverables

Software deliverables will include:
-	A unified OT/SB/MFC/MFG solver which is not currently available.  This will be built around Firedrake, building upon the work of Natale and Todeschi.

Natale, Andrea, and Gabriele Todeschi. "A mixed finite element discretization of dynamical optimal transport." Journal of Scientific Computing 91, no. 2 (2022): 38.
