---
title: "PDE-driven Digital Twins"

department: "Mathematics"

date: "10/02/2024"
author: 
    name: "Prof Colin Cotter"
    affiliation: "Imperial"
institution: "Imperial"
---
## Project Description

   There are many definitions for digital twins but here we define a
   digital twin as a computational model of a physical (natural,
   engineered, social or hybrid) system combined with algorithms for
   assimilating observed data into the model and for controlling the
   physical system so that there is bidirectional interaction updated
   in real time. Some applications include: flood forecasting with
   river control, vertical farming, renewable energy devices, traffic
   pollution control in cities, etc.

   This topic is for PhD researchers who are interested in numerical
   discretisations for PDEs and their embedding inside algorithms that
   couple them with data.

### Existing background work

    The lead supervisor is an expert in data assimilation (having
    written a textbook with Sebastian Reich) and also in finite
    element discretisations of PDEs.

### Main objectives of the project

   In this project topic we will focus on the algorithmic challenges
   arising when the computational model involves the numerical
   solution of PDEs.  In this case, to realise the full potential uses
   of digital twins, we need to develop new mathematics and algorithms
   to address the challenge to computational resources that otherwise
   exists. This includes: multiscale and multifidelity modelling,
   reduced order modelling, empirical surrogates (including generative
   models) and hybrid empirical/mechanistic models, data assimilation
   and control algorithms, all of which may need to be federated into
   a fully functional digital twin.

   Projects in this topic will focus in one or more of this algorithmic
   areas, developed in the context of finite element methods for partial
   differential equations, with the application area open depending
   on the interests and capabilities of the PhD researcher.

### Details of Software/Data Deliverables

The project will deliver software for the chosen algorithms, so that
they can be evaluated and extended. The software will take the form of
a general purpose tool that can be applied to a range of models
implemented using the Firedrake framework.
