---
title: "Large-scale high-performance solver for therapeutic ultrasound applications"
institution: "UCL"
department: "UCL Division of Surgery and Interventional Science"
author: "Timo Betcke"
date: "11/10/2024"
advisor: "Dr Pierre Gélat"

---
## Project Description

### Existing background work

The supervisory team, together with Dr van ’t Wout, has been developing the open-source Python library OptimUS for solving acoustic wave propagation in an unbounded medium in 3D with piecewise homogeneous domains. OptimUS solves the Helmholtz equation using the boundary element method (BEM). It has been used to simulate biomedical ultrasound clinical scenarios relating to treating cancers of the liver and kidney1, as well as osteoid osteoma2. OptimUS featured as part of an international software benchmarking exercise3 for ultrasound transcranial neuromodulation, overseen by the International Transcranial Ultrasonic Stimulation Safety and Standards. The OptimUS library is being used in biomedical ultrasound research in academic institutions worldwide as well as a pedagogical tool for undergraduate and postgraduate students. OptimUS leverages the Bempp kernel developed by Prof Betcke.

Using OptimUS to solve large biomedical problems at high frequencies is currently challenging due to the large RAM consumption required, which is of the order of GigaByte to TeraByte. A dedicated high-frequency solver is therefore required to achieve realistic simulations at the operational MHz frequencies relevant to laboratory and clinical biomedical ultrasound applications. A promising kernel-independent Fast Multipole Method (FMM) BEM has recently been developed for the next release of the Bempp library and has been used to solve the Laplace equation. Research into dedicated high-frequency FMM implementation is needed to achieve BEM simulations on a larger scale than other numerical approaches. BEM has a distinct advantage over finite element and finite-difference time domain schemes as it suffers from only minimal numerical dispersion and pollution effects. It is therefore anticipated that the development of a high-performance FMM BEM formulation for Helmholtz kernels will be transformative in the field of biomedical ultrasound.

### Main objectives of the project

This project aims to develop an efficient FMM BEM formulation for high-frequency Helmholtz kernels. The new formulation will be implemented in the OptimUS software, validated against analytical solutions for canonical geometries, and tested in simulations of ultrasound wave propagation through the human body using anatomical models derived from MRI/CT images. This formulation will also be used as a basis for treating the physics of weakly nonlinear wave propagation in tissue, which requires solving inhomogeneous Helmholtz equations for higher order harmonics. The performance of this new solver will be benchmarked against existing CPU implementations and will also be tested alongside the spectral element method solver recently developed by Prof Garth Wells’ team at University of Cambridge. It will also be benchmarked against other toolboxes used by the biomedical ultrasound community (e.g. k-Wave)

The successful completion of this project will have significant implications for the field of biomedical ultrasound, particularly in treatment planning for procedures like focused ultrasound therapy as well as imaging applications such as acoustic tomography. By improving the accuracy and efficiency of simulations, this work will enhance OptimUS and facilitate its wider adoption in clinical settings, where it could be used for personalised treatment plans based on anatomical models derived from MRI/CT scans, ultimately improving patient outcomes.

The supervisory team and the external partners will offer academic mentorship, educational support and access to the state-of-the-art facilities required for the successful delivery of this project. These facilities include high-performance computing workstations as well as the UCL Research Computing Platforms Service.

### Details of Software/Data deliverables

The project involves implementing, testing and optimising the computational performance of new BEM formulations for solving ultrasound waves in piecewise homogeneous and heterogeneous domains. The student will be actively involved in software development using Rust and Python, employing best practices in software carpentry including version control with Git and automated testing to ensure code reliability and reproducibility. The outcome of this project will impact the field of biomedical ultrasound, specifically for treatment planning, and facilitate the uptake of OptimUS in focused ultrasound treatment platforms used in the clinic.

### References

- Haqshenas, S.R., Gélat, P., van’t Wout, E., Betcke, T. and Saffari, N., 2021. A fast full-wave solver for calculating ultrasound propagation in the body. Ultrasonics, 110, p.106240.
- van't Wout, E., Haqshenas, S.R., Gélat, P., Betcke, T. and Saffari, N., 2022. Frequency-robust preconditioning of boundary integral equations for acoustic transmission. Journal of Computational Physics, 462, p.111229.
- Aubry, J.F., Bates, O., Boehm, C., Butts Pauly, K., Christensen, D., Cueto, C., Gélat, P., Guasch, L., Jaros, J., Jing, Y. and Jones, R., 2022. Benchmark problems for transcranial ultrasound simulation: Intercomparison of compressional wave models. The Journal of the Acoustical Society of America, 152(2), pp.1003-1019.
