---
title: "The propagation of uncertainties across coupled climate models"

department: "Statistics"

date: "10/20/2024"
author: 
    name: "Prof Serge Guillas"
    affiliation: "UCL"
---
## Project Description

### Existing background work

The propagation of uncertainties across coupled models is a grand challenge, not yet with a solution for climate (ocean, sea-ice, atmosphere, land, etc.). The resources and runtimes required by simulations at different scales differ vastly. Linking models through emulators is now ripe (Ming, D. and Guillas, S. (2021) Linked Gaussian process emulation for systems of computer models using Matérn kernels and adaptive design, SIAM/ASA Journal on Uncertainty Quantification. 9(4), 1615-1642.) and representations such as Deep Gaussian Processes (Ming, D., Williamson, D., and Guillas, S. (2023) Deep Gaussian process emulation using stochastic imputation. Technometrics. 65(2), 150-161) are available, but the software, and the practical and methodological challenges require investigations. There is great interest at the Met Office, and at UKAEA, since coupling of multiple models is a necessary step in these complex models. The community has not yet addressed this issue head-on, so this is a timely project to deliver some initial groundbreaking steps.
The principal supervisor and collaborators have set up software platforms, within a prior project at the Alan Turing Institute, with the Multi-Output Gaussian Process Emulator (MOGP), and within the EPSRC project SEAVEA (2021-2025), a set-up that facilitates the design and organisation of runs. For applications to climate modelling the group of Prof Guillas has been working on the topic, but with only one submodel, with a paper now under submission: D. Giles, J. Briant, C. J. Morcrette, S. Guillas, “Sensitivity of simulated tropical precipitation in a coarse climate model to the inclusion of subgrid variability machine learnt from high resolution weather simulations”. 


### Main objectives of the project

The objectives are to create surrogates of sub-models and link them within a network of models, merging some simulators, some emulators. The network can be viewed as a Deep Gaussian Process with partial exposure of the hidden layers (via individual runs of the simulators). Challenges include the dimensions to reduce to forward the right level of information across the network, the construction of uncertainties within such a hybrid set-up, and the design of such computer experiments. Campaigns of runs will be co-designed with the Met Office, which will provide computing access to novel facilities.
### Details of Software/Data Deliverables

### Software and Data Developments

The codes are now available to start with linked emulators and Deep Gaussian Processes (R and python: [https://github.com/mingdeyu/DGP](https://github.com/mingdeyu/DGP)), and the dimension reduction and emulation of multi-outputs (MOGP in python: [https://github.com/alan-turing-institute/mogp-emulator](https://github.com/alan-turing-institute/mogp-emulator)). Developments include managing and optimising the creation of the overall network of models, including uncertainties, with an emphasis on memory requirements due to large dimensions and the trade-off of computation v. accuracy, ultimately at the exascale.
