---
title: "Data-driven multi-scale modelling of bacterial biofilms"
institution: "UCL"
department: "Mathematics"
author: "Laura Beer"
date: "02/10/2024"
advisor: "Dr. Philip Pearce"

---
## Project Description

 ### Existing background work

Bacterial biofilms are communities of bacterial cells embedded in extracellular matrix, and are the most common form of bacterial life. Numerous software packages exist for performing cell-based simulation of bacterial biofilms and synthetic bacterial communities (e.g. iDynoMiCS, BSim, gro). However, such software does not typically allow for flexibility in the properties of extracellular matrix proteins, which we have found in previous work to provide both structural integrity (Hartmann et al., Nat. Phys., 2019; Pearce et al., Phys. Rev. Lett. 2019) and protection from antibiotics (Böhning et al., Nat. Comm., 2023) in bacterial biofilms. There is therefore a crucial gap in the software landscape, which limits our ability to understand and test fundamentally how bacterial communities respond to antibiotic treatment in a range of conditions. Recent experimental data generated by our collaborators has revealed the structure, chemical properties and spatial arrangement of the molecules that make up the extracellular matrix in biofilms, providing an opportunity to close this gap through data-driven coarse-grained models and codes for biomolecular dynamics within bacterial biofilms.

### Main objectives of the project

In this project, we will develop a computational workflow to take in molecular-level detail about matrix proteins and output coarse-grained models of bacterial biofilms that account for matrix properties. We will realise the following objectives:

1. Develop a workflow to take in experimental data on the molecular structure and properties of matrix proteins and output coarse-grained molecular properties for use in cell-based simulations, validated where possible by mesoscopic experimental data such as phase diagrams.
2. Perform simulations of bacterial biofilms including such extracellular matrix proteins and explore their effect on antitbiotic treatment, validated by data on molecular organisation and antibiotic transport in biofilms.
3. Integrate the workflow and code into new and/or existing software so that molecular data can be quickly converted into new coarse-grained particles in cell-based models.

### Details of Software/Data Deliverables

- Software to convert molecular data to coarse-grained models.
- Software to include the microscopic properties of matrix proteins in cell-based models.
