---
title: "Aligned diffusion models for machine learning"

department: "Mathematics"

date: "10/18/2024"
author: 
    name: "Dr Felipe Tobar"
    affiliation: "Imperial"
institution: "Imperial"
---
## Project Description

### Existing background work

Diffusion models (DM) are the state of the art on generative modelling, their ability to learn (implicit) probabilistic models over complex structured datasets is unparalleled and it has been validated on images and audio in a number of applications. The generality and wide applicability of DMs motivates a variety of research directions including fairness, reinforcement-learning-based enhancement, prevention of mode collapse, AI alignment, and accelerated computation. Alignment, in particular, is a much-desired feature in DMs as they are currently being deployed for use by the general public, where they might deal with sensitive data and critical decision making. 
 
We have developed fine-tuning techniques for DM with the principal aim of aligning the samples generated by the DM to human criteria. Our contributions have been tested on novel DM samplers that follow objectives that are difficult to describe by a standard discriminant function. This includes producing samples that are aesthetic, incompressible, or that do not include violent content (e.g., explicit images).

### Main objectives of the project

To design and validate strategies to align diffusion models with human criteria. The project comprises both theoretical and computational aspects. 

- To explore the state of the art in DMs and the techniques currently used for guidance and finetuning. 
- To understand current alignment techniques using, e.g., guidance and reinforcement learning
- To identify which tools in the ML literature and related resources from computational mathematics, optimisation, statistics, and probability, can be used to propose control (alignment) loops for sampling in DMs
- To design an experiment, and an experimental setup, to validate the proposed alignment techniques in applications involving fairness, social sciences, health, or general generative modelling
- To analyse, both from theoretical and practical perspectives, the developed alignment techniques so as to provide convincing evidence of alignment in DMs
- To ensure availability and dissemination of the project contributions in the form of free (open source) software which is compatible with other toolbox of the ML community

### Details of Software Deliverables

The conceptual contributions of the project are expected to be complemented with reproducible experimental validation. This includes i) open-source software to be used by the scientific community, ii) a public repository hosting the developed software, iii) reproducible examples showing applications to scientific or social challenges.
Describe coding and data developments during the project.
See above.

