on:
  workflow_dispatch:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main ]

name: Test website rendering

jobs:
  build-deploy:
    name: Build website
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2
